# .github/workflows/main.yml

name: Build for Windows & macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    name: Build Windows (x64)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Install backend dependencies
        run: npm ci --prefix backend

      - name: Build and package Windows application
        run: npm run package -- --win

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeyVault-Windows-x64-Setup
          path: dist/*.exe

  build-macos:
    name: Build macOS (ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Install backend dependencies
        run: npm ci --prefix backend

      - name: Build and package macOS application
        run: npm run package -- --mac

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeyVault-macOS-ARM64-Build
          path: dist/*.dmg