# .github/workflows/build-mac.yml

name: Build macOS Universal App

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Triggers the workflow on push events to the main branch
  pull_request:
    branches: [ "main" ] # Optional: Triggers the workflow on pull requests to the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies for the root, frontend, and backend
      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install backend dependencies
        run: npm install --prefix backend

      # 4. Run the build script defined in your package.json
      - name: Build and package macOS application
        run: npm run package -- --mac universal
        env:
          # This is required by electron-builder for macOS builds
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      # 5. Upload the generated DMG file as a build artifact
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeyVault-macOS-Universal-Build
          path: dist/*.dmg