# .github/workflows/main.yml

name: Build Portable Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # --- Windows 构建工作 ---
  build-windows:
    name: Build Windows Portable (x64)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix frontend
        shell: bash

      - name: Build and package Windows application
        run: npm run package -- --win --x64
      
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keyvault-windows-x64-portable
          path: dist/*.zip

  # --- macOS 构建工作 ---
  build-macos:
    name: Build macOS (ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix frontend

      - name: Build and package macOS application
        run: npm run package -- --mac --arm64

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keyvault-macos-arm64-build
          path: dist/*.dmg